In [ ]:
#List

In [27]:
#Membuat List
warna = ['merah', 'jingga', 'kuning', 'hijau', 'biru', 'nila', 'ungu']
bulat = [10, 25, 67, -81, 93, -1]
desimal = [3.6, 1.2, 9.5, 7.6, 4.2]
kondisi = [True, True, True, False, False]
print (warna)
type(warna)

['merah', 'jingga', 'kuning', 'hijau', 'biru', 'nila', 'ungu']


list

In [28]:
print(bulat)
print(desimal)
print(kondisi)

[10, 25, 67, -81, 93, -1]
[3.6, 1.2, 9.5, 7.6, 4.2]
[True, True, True, False, False]


In [29]:
novel = ['Laskar Pelangi', 'Andrea Hirata', 2008, 529, 5.56, True]
print(novel)

['Laskar Pelangi', 'Andrea Hirata', 2008, 529, 5.56, True]


In [30]:
pixel = [[1,0,1],
         [0,1,0],
         [1,0,1]
        ]
print(pixel)

[[1, 0, 1], [0, 1, 0], [1, 0, 1]]


In [31]:
kota = [['Jakarta', 5, 664.01],
        ['Banjarmasin', 98.46],
        ['Lampung'],
        ['Jayapura', 5, 626.7],
        ['Makassar', 15]]
print(kota)

[['Jakarta', 5, 664.01], ['Banjarmasin', 98.46], ['Lampung'], ['Jayapura', 5, 626.7], ['Makassar', 15]]


In [32]:
word = []
print(word)
type(word)

[]


list

In [35]:
print(len(warna))
print(len(bulat))
print(len(desimal))
print(len(kondisi))
print(len(novel))
print(len(word))

7
6
5
5
6
0


In [36]:
#List Indexing & Slicing
warna = ['merah', 'jingga', 'kuning', 'hijau', 'biru', 'nila', 'ungu']
bulat = [10, 25, 67, -81, 93, -1]
desimal = [3.6, 1.2, 9.5, 7.6, 4.2]
kondisi = [True, True, True, False, False]
novel = ['Laskar Pelangi', 'Andrea Hirata', 2008, 529, 5.56, True]

print(warna[1])
print(bulat[3])
print(desimal[4])
print(kondisi[2])
print(novel[0])

print(warna[-1])
print(bulat[-2])
print(desimal[-3])
print(kondisi[-4])
print(novel[-5])

print(f"warna = {warna}")

warna[0] = 'RED'
warna[3] = 'GREEN'
warna[-3] = 'BLUE'

print(f"warna = {warna}")

jingga
-81
4.2
True
Laskar Pelangi
ungu
93
9.5
True
Andrea Hirata
warna = ['merah', 'jingga', 'kuning', 'hijau', 'biru', 'nila', 'ungu']
warna = ['RED', 'jingga', 'kuning', 'GREEN', 'BLUE', 'nila', 'ungu']


In [8]:
print(warna[-1])
print(bulat[-2])
print(desimal[-3])
print(kondisi[-4])
print(novel[-5])

ungu
d
0.6
sakit
jika kita tak pernah jatuh cinta


In [9]:
print(f"warna = {warna}")
warna[0] = 'RED'
warna[3] = 'GREEN'
warna[-3] = 'BLUE'

print(f"warna = {warna}")

warna = ['RED', 'jingga', 'kuning', 'GREEN', 'BLUE', 'nila', 'ungu']
warna = ['RED', 'jingga', 'kuning', 'GREEN', 'BLUE', 'nila', 'ungu']


In [10]:
print(warna[2:5])
print(bulat[1:3])
print(desimal[2:5])
print(kondisi[0:4])
print(novel[-5:-3])

['kuning', 'GREEN', 'BLUE']
['b', 'c']
['0.6', '0.7', '0.8']
['sehat', 'sakit', 'lelah', 'fit']
['jika kita tak pernah jatuh cinta', 'loneliness']


In [11]:
print(warna, '\n')

print(warna[3:], '\n')
print(warna[:3], '\n')

print(warna[-5:], '\n')
print(warna[:-5], '\n')

['RED', 'jingga', 'kuning', 'GREEN', 'BLUE', 'nila', 'ungu'] 

['GREEN', 'BLUE', 'nila', 'ungu'] 

['RED', 'jingga', 'kuning'] 

['kuning', 'GREEN', 'BLUE', 'nila', 'ungu'] 

['RED', 'jingga'] 



In [12]:
#Manipulasi Elemen List
cuaca = ['cerah']
print(cuaca)

cuaca.append('berawan')
cuaca.append('hujan ringan')
cuaca.append('hujan lebat')
cuaca.append('berangin')

print(cuaca)

['cerah']
['cerah', 'berawan', 'hujan ringan', 'hujan lebat', 'berangin']


In [13]:
angka = [1,2,3]
huruf = ['a', 'b', 'c']
alphanumeric = angka + huruf
alphanumeric

[1, 2, 3, 'a', 'b', 'c']

In [18]:
'cerah' in cuaca

True

In [19]:
'panas' in cuaca

False

In [20]:
'dingin' not in cuaca

True

In [21]:
'berawan' not in cuaca

False

In [22]:
cuaca.index('hujan lebat')

3

In [23]:
cuaca.index('hujan ringan')

2

In [24]:
temp = [10, -2, 0.5, -0.75, 50, 4, -1]
nama = ['Agung', 'ani', 'bernard', 'Bagus', 'Tini', 'toriq']

temp.sort()
print(temp)

print(sorted(nama))
print(nama)

[-2, -1, -0.75, 0.5, 4, 10, 50]
['Agung', 'Bagus', 'Tini', 'ani', 'bernard', 'toriq']
['Agung', 'ani', 'bernard', 'Bagus', 'Tini', 'toriq']


In [1]:
temp = [10, -2, 0.5, -0.75, 50, 4, -1]
nama = ['Agung', 'ani', 'bernard', 'Bagus', 'Tini', 'toriq']

temp.sort(reverse=True)
print(temp)

print(sorted(nama, reverse=True))
print(nama)

[50, 10, 4, 0.5, -0.75, -1, -2]
['toriq', 'bernard', 'ani', 'Tini', 'Bagus', 'Agung']
['Agung', 'ani', 'bernard', 'Bagus', 'Tini', 'toriq']


In [2]:
pets = ['cat', 'dog', 'rabbit', 'fish', 'turtle', 'hamster', 'bird']
print(pets)

del pets[3]
print(pets)

pets.remove('dog')
print(pets)

pets.clear()
print(pets)

['cat', 'dog', 'rabbit', 'fish', 'turtle', 'hamster', 'bird']
['cat', 'dog', 'rabbit', 'turtle', 'hamster', 'bird']
['cat', 'rabbit', 'turtle', 'hamster', 'bird']
[]


In [3]:
class_ori = ['dammam', 'frontera', 'nurion', 'pangea', 'param']
class_salin = class_ori

print(class_ori)
print(class_salin)

['dammam', 'frontera', 'nurion', 'pangea', 'param']
['dammam', 'frontera', 'nurion', 'pangea', 'param']


In [4]:
class_ori.remove('dammam')
class_salin.append('maru')

print(class_ori)
print(class_salin)

['frontera', 'nurion', 'pangea', 'param', 'maru']
['frontera', 'nurion', 'pangea', 'param', 'maru']


In [6]:
class_ori = ['dammam', 'frontera', 'nurion', 'pangea', 'param']
class_salin = class_ori.copy()

print('ori :', class_ori)
print('salinan :', class_salin, '\n')

class_ori.remove('dammam')
class_salin.append('maru')

print('ori :', class_ori)
print('salinan :', class_salin, '\n')

ori : ['dammam', 'frontera', 'nurion', 'pangea', 'param']
salinan : ['dammam', 'frontera', 'nurion', 'pangea', 'param'] 

ori : ['frontera', 'nurion', 'pangea', 'param']
salinan : ['dammam', 'frontera', 'nurion', 'pangea', 'param', 'maru'] 



In [7]:
nilai = [90, 80, 70]
tugas, uts, uas = nilai
score = (tugas + uts + uas)/3

print(f"tugas\t: {tugas}, uts: {uts}, uas: {uas}\nskor\t: {score}")

tugas	: 90, uts: 80, uas: 70
skor	: 80.0


In [ ]:
#TUple

In [8]:
warna = 'merah', 'jingga', 'kuning', 'hijau', 'biru', 'nila', 'ungu'
bulat = 10, 25, 67, -81, 93, -1
desimal = (3.6, 1.2, 9.5, 7.6, 4.2)
kondisi = (True, True, True, False, False)

print(warna)
print(bulat)
print(desimal)
print(kondisi)

type(warna)

('merah', 'jingga', 'kuning', 'hijau', 'biru', 'nila', 'ungu')
(10, 25, 67, -81, 93, -1)
(3.6, 1.2, 9.5, 7.6, 4.2)
(True, True, True, False, False)


tuple

In [9]:
novel = 'Sang Pemimpi', 'Andrea Hirata', 2006, 292, 5.5, True

negara = (('Tiongkok', 1415.1),
          ('India', False),
          ('USA', 337.6, False, 4.34),
          ('Indonesia', 272.229, True)
         )

pixel = ((0,1,0),
         (1,0,1),
         (0,1,0))

print(novel)
print(negara)
print(pixel)

('Sang Pemimpi', 'Andrea Hirata', 2006, 292, 5.5, True)
(('Tiongkok', 1415.1), ('India', False), ('USA', 337.6, False, 4.34), ('Indonesia', 272.229, True))
((0, 1, 0), (1, 0, 1), (0, 1, 0))


In [10]:
angka = [1, 2, 3, 4, 5]
angka = tuple(angka)

print(angka)
type(angka)

(1, 2, 3, 4, 5)


tuple

In [12]:
huruf = ('a', 'b', 'c', 'd', 'e')
huruf = list(huruf)

print(huruf)
type(angka)

['a', 'b', 'c', 'd', 'e']


tuple

In [15]:
warna = 'merah', 'jingga', 'kuning', 'hijau', 'biru', 'nila', 'ungu'

print(warna[5])
print(warna[-6], '\n')

print(warna[1:4])
print(warna[-4:-1], '\n')

print(warna[5:1])
print(warna[-3], '\n')

print(warna[:3])
print(warna[:-2], '\n')

nila
jingga 

('jingga', 'kuning', 'hijau')
('hijau', 'biru', 'nila') 

()
biru 

('merah', 'jingga', 'kuning')
('merah', 'jingga', 'kuning', 'hijau', 'biru') 



In [21]:
warna = ['merah', 'jingga', 'kuning', 'hijau', 'biru', 'nila', 'ungu']

warna[0] = 'RED'
warna[3] = 'GREEN'
warna[4] = 'BLUE'

print(warna)

['RED', 'jingga', 'kuning', 'GREEN', 'BLUE', 'nila', 'ungu']


In [22]:
warna.append('black')

In [24]:
warna.clear()

In [ ]:
#Dictionary

In [25]:
myPet = {'nama' : 'Imut', 
         'jenis':'kucing', 
         'warna':'jingga', 
         'umur':1.5, 
         'jenis_kelamin':0, 
         'vaksin':False}
print(myPet)

{'nama': 'Imut', 'jenis': 'kucing', 'warna': 'jingga', 'umur': 1.5, 'jenis_kelamin': 0, 'vaksin': False}


In [37]:
kelas = {'kelas':'Bravolexta',
         'student' :40,
         'nama':('Anindya','David', 'Rengga', 'Nurul', 'Yusup'),
         'nilai':[90.5, 55.1, 60, 71.5, 85.6],
         'lulus':(True, False, False, True, True)
        }
print(kelas)
type(kelas)

{'kelas': 'Bravolexta', 'student': 40, 'nama': ('Anindya', 'David', 'Rengga', 'Nurul', 'Yusup'), 'nilai': [90.5, 55.1, 60, 71.5, 85.6], 'lulus': (True, False, False, True, True)}


dict

In [38]:
buah = ['apel', 'mangga', 'jeruk', 'pisang', 'manggis']
jumlah = [10, 5, 15, 6, 21]

gudang = dict(zip(buah,jumlah))

print(gudang)
type(gudang)

{'apel': 10, 'mangga': 5, 'jeruk': 15, 'pisang': 6, 'manggis': 21}


dict

In [39]:
gudang.keys()
gudang.values()
gudang.items()

dict_items([('apel', 10), ('mangga', 5), ('jeruk', 15), ('pisang', 6), ('manggis', 21)])

In [96]:
'menteng' in gudang.keys()

False

In [41]:
'manggis' not in gudang.keys()

False

In [42]:
10 in gudang.keys()

False

In [43]:
100 not in gudang.values()

True

In [44]:
print(gudang)

print('Jumlah apel = ', gudang['apel'])
print('Jumlah mangga = ', gudang['mangga'])
print('Jumlah jeruk = ', gudang['jeruk'])
print('Jumlah pisang = ', gudang['pisang'])
print('Jumlah manggis = ', gudang['manggis'])

{'apel': 10, 'mangga': 5, 'jeruk': 15, 'pisang': 6, 'manggis': 21}
Jumlah apel =  10
Jumlah mangga =  5
Jumlah jeruk =  15
Jumlah pisang =  6
Jumlah manggis =  21


In [49]:
print(gudang)

#Restock
gudang['apel'] = 100
gudang['mangga'] = 150
gudang['jeruk'] = 105
gudang['pisang'] = 50
gudang['manggis'] =71
print(gudang)

{'apel': 100, 'mangga': 150, 'jeruk': 105, 'pisang': 50, 'manggis': 71}
{'apel': 100, 'mangga': 150, 'jeruk': 105, 'pisang': 50, 'manggis': 71}


In [53]:
print(gudang)

print('Jumlah apel = ', gudang.get('apel'))
print('Jumlah mangga = ', gudang.get('mangga'))
print('Jumlah jeruk = ', gudang.get('jeruk'))
print('Jumlah pisang = ', gudang.get('pisang'))
print('Jumlah manggis = ', gudang.get('manggis'))

{'apel': 100, 'mangga': 150, 'jeruk': 105, 'pisang': 50, 'manggis': 71}
Jumlah apel =  100
Jumlah mangga =  150
Jumlah jeruk =  105
Jumlah pisang =  50
Jumlah manggis =  71


In [54]:
print('Jumlah Jamblang = ', gudang.get('jamblang', 'Stok jamblang kosong !'))

Jumlah Jamblang =  Stok jamblang ksoong !


In [58]:
gudang['apel':'pisang']
gudang['jeruk':]
gudang[:'manggis']

TypeError: unhashable type: 'slice'

In [60]:
nasabah = {'Andini':5000,
           'Ganes':4500,
           'Chandra':5250,
           'Dita':6000}
print(nasabah)

nasabah['Indy'] = 7000
nasabah['Devi'] = 3000
nasabah['Rifky'] = 2500
print(nasabah)

{'Andini': 5000, 'Ganes': 4500, 'Chandra': 5250, 'Dita': 6000}
{'Andini': 5000, 'Ganes': 4500, 'Chandra': 5250, 'Dita': 6000, 'Indy': 7000, 'Devi': 3000, 'Rifky': 2500}


In [61]:
print(nasabah, '\n')
del nasabah['Ganes']
del nasabah['Rifky']
print(nasabah, '\n')

pesan = 'Nasabah tidak ditemukan'
nasabah.pop('Chandra', pesan)
nasabah.pop('Zul',pesan)
print(nasabah, '\n')

nasabah.clear()
print(nasabah)

{'Andini': 5000, 'Ganes': 4500, 'Chandra': 5250, 'Dita': 6000, 'Indy': 7000, 'Devi': 3000, 'Rifky': 2500} 

{'Andini': 5000, 'Chandra': 5250, 'Dita': 6000, 'Indy': 7000, 'Devi': 3000} 

{'Andini': 5000, 'Dita': 6000, 'Indy': 7000, 'Devi': 3000} 

{}


In [ ]:
#Set

In [62]:
A = {1, 2, 3}
print(A)
type(A)

{1, 2, 3}


set

In [63]:
nama = 'febry'
nama = set(nama)
print(nama)
type(nama)

karakter = [6, 5, 2, 18, 25]
karakter = set(karakter)
print(karakter)
type(karakter)

{'r', 'f', 'e', 'b', 'y'}
{2, 5, 6, 18, 25}


set

In [64]:
label = [1, 1, 1, 0, 0, 3, 3, 3, 2, 2, 0, 3, 1, 2]
label = set(label)
print(label)

{0, 1, 2, 3}


In [65]:
nama = 'Yusup Hidayat Winata'
nama = set(nama)
print(nama)

{'H', 'd', 'a', 'n', ' ', 'W', 'p', 'y', 'Y', 'i', 'u', 's', 't'}


In [70]:
iris = ['virginica', 'versicolor', 'setosa']

In [73]:
x = iris[0]
print(x)
iris[0:1]

virginica


['virginica']

In [78]:
iris = {'virginica', 'versicolor', 'setosa'}
print(iris,'\n')

iris.add('ayame')
iris.add('sweet')
iris.add('confusa')
iris.add('setosa')
print(iris,'\n')

iris.remove('virginica')
iris.remove('versicolor')
iris.remove('setosa')
print(iris,'\n')

{'setosa', 'versicolor', 'virginica'} 

{'confusa', 'versicolor', 'virginica', 'setosa', 'sweet', 'ayame'} 

{'confusa', 'sweet', 'ayame'} 



In [79]:
A = {1,2,3,5}
B = {3,5,6,7}

# A irisan B
irisan = A.intersection(B)
print(irisan)

# A gabungan B
gabungan = A.union(B)
print(gabungan)

{3, 5}
{1, 2, 3, 5, 6, 7}


In [82]:
#Array

In [4]:
import numpy as np
number = np.array([12, 3, 5, 6 , 0, -1, -2])
print(number)
type(number)

[12  3  5  6  0 -1 -2]


numpy.ndarray

In [84]:
huruf = ['Z', 'R', 'A', 'Q', 'W']
huruf = np.array(huruf)
print(huruf)
type(huruf)

['Z' 'R' 'A' 'Q' 'W']


numpy.ndarray

In [85]:
number = np.array([12, 3, 5, 6 ,0, -1, -2], dtype=float)
print(number)
type(number)

[12.  3.  5.  6.  0. -1. -2.]


numpy.ndarray

In [86]:
number = np.array([12, 3, 5, 6 ,0, -1, -2], dtype=str)
print(number)
type(number)

['12' '3' '5' '6' '0' '-1' '-2']


numpy.ndarray

In [87]:
number = np.array([12, 3, 5, 6 ,0, -1, -2], dtype=bool)
print(number)
type(number)

[ True  True  True  True False  True  True]


numpy.ndarray

In [88]:
M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]], 
              dtype=int)
print(M)
type(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [90]:
print('Size : ', number.size)
print('Dimension : ', number.ndim)
print('Shape : ', number.shape, '\n')

print('Size : ', M.size)
print('Dimension : ', M.ndim)
print('Shape : ', M.shape)

Size :  7
Dimension :  1
Shape :  (7,) 

Size :  9
Dimension :  2
Shape :  (3, 3)


In [95]:
nol_kecil = np.zeros(5) # ordo 5x1
nol_besar = np.zeros((3,3), dtype=int) #ordo 4x4

print(nol_kecil, '\n')
print(nol_besar, '\n')

[0. 0. 0. 0. 0.] 

[[0 0 0]
 [0 0 0]
 [0 0 0]] 



In [98]:
vecor_1 = np.ones(10)
matriks_1 = np.ones((4,4), dtype=int)

print(vecor_1, '\n')
print(matriks_1, '\n')

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] 



In [99]:
vector_range = np.arange(9)
matriks_range = vector_range.reshape(3,3)

print(vector_range, '\n')
print(matriks_range, '\n')

[0 1 2 3 4 5 6 7 8] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 



In [100]:
lang = np.array(['id', 'en', 'jp', 'cn', 'ru', 'kr', 'th'])

print(lang,'\n')
print(lang[0], '\n')
print(lang[-1], '\n')

print(lang[1:4], '\n')
print(lang[-3:-2], '\n')

print(lang[3:], '\n')
print(lang[:6], '\n')

print(lang[-5:], '\n')
print(lang[:-3], '\n')

['id' 'en' 'jp' 'cn' 'ru' 'kr' 'th'] 

id 

th 

['en' 'jp' 'cn'] 

['ru'] 

['cn' 'ru' 'kr' 'th'] 

['id' 'en' 'jp' 'cn' 'ru' 'kr'] 

['jp' 'cn' 'ru' 'kr' 'th'] 

['id' 'en' 'jp' 'cn'] 



In [102]:
lang = np.array (['id', 'en', 'jp', 'cn','ru','kr','th'])
print(lang,'\n')

lang[4] = 'CA'
lang[5] = 'AR'
lang[-1] = 'HI'
lang[:4] = 'no'

print(lang, '\n')

['id' 'en' 'jp' 'cn' 'ru' 'kr' 'th'] 

['no' 'no' 'no' 'no' 'CA' 'AR' 'HI'] 



In [103]:
A = np.array([[81, 24, 36],
              [43, 67, 12],
              [75, 90, 58]])
print(A, '\n')

print(A[1,2]) # baris 1 kolom 2
print(A[2,0]) # baris 2 kolom 0
print(A[0,1]) # baris 0 kolom 1

[[81 24 36]
 [43 67 12]
 [75 90 58]] 

12
75
24


In [5]:
B = np.array([[81, 24, 36],
              [43, 67, 12],
              [75, 90, 58]])
print(B, '\n')

print(B[0:3, 0:2],'\n')
print(B[1:2, 1:2],'\n')
print(B[0:2, :],'\n')
print(B[:, 2:3],'\n')
print(B[1:, 1:],'\n')
print(B[:2, :2],'\n')

[[81 24 36]
 [43 67 12]
 [75 90 58]] 

[[81 24]
 [43 67]
 [75 90]] 

[[67]] 

[[81 24 36]
 [43 67 12]] 

[[36]
 [12]
 [58]] 

[[67 12]
 [90 58]] 

[[81 24]
 [43 67]] 



In [6]:
B[0:2, :] = '70'
print(B, '\n')

[[70 70 70]
 [70 70 70]
 [75 90 58]] 



In [6]:
X = np.array([[1,2,3], [4,5,6], [7,8,9]])
Y = np.array([[2,2,2], [2,2,2], [2,2,2]])
skalar = 3

In [7]:
#penambahan
A = X + skalar
Z = X + Y

print(A, '\n\n', Z)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

 [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [8]:
#pengurangan
A = X - skalar
Z = X - Y

print(A, '\n\n', Z)

[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]] 

 [[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


In [9]:
#dot product
A = X * skalar
Z = X * Y

print(A, '\n\n', Z)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]] 

 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [11]:
# perkalian
Z = np.matmul(X, Y)

print(Z)

[[12 12 12]
 [30 30 30]
 [48 48 48]]


In [12]:
# mencari determinan matriks
Z = X * X
det_Z = np.linalg.det(Z)
print(det_Z)

-216.00000000000006


In [13]:
# mencari determinan matriks
Z = X * X
inv_Z = np.linalg.inv(Z)
print(inv_Z)

[[ 1.29166667 -1.16666667  0.375     ]
 [-2.16666667  1.66666667 -0.5       ]
 [ 0.93055556 -0.61111111  0.18055556]]


In [14]:
print(X,'\n')
X_T = X.transpose()
print(X_T)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [15]:
print(X,'\n')
flat_T = X.flatten()
print(flat_T)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3 4 5 6 7 8 9]


In [ ]:
#Latihan

In [33]:
#1
tabel = {"NIK": ["1990022","2001077","2002019","2002081","2005099","2006003","2006104","2008160"],
         "Nama" : ["Herman", "Badar", "Clara", "Rista", "Riani", "Afif", "Riven", "Endah"],
         "Jenis_Kelamin" : ["L","L","P","P","P","L","L","P"],
         "Alamat" : ["Tangerang","Bekasi","Depok","Bogor","Bekasi","Karawang","Tangerang","Jakarta"],
         "Divisi" : ["Machinery","Machinery","Compressor","QC","QC","Compressor","Compressor","Machinery"],
         "Jabatan" : ["Manager","Staff","Staff","Staff","Operator","Operator","Operator","Operator"],
         "Gaji_Pokok" : [100000,7500000,7000000,6500000,6000000,5500000,5500000,5000000]
    
}

#print(tabel)

print("NIK", tabel.get("NIK"), "\n")
print("Nama", tabel.get("Nama"), "\n")
print("Jenis Kelamin", tabel.get("Jenis_Kelamin"), "\n")
print("Alamat", tabel.get("Alamat"), "\n")
print("Divisi", tabel.get("Divisi"), "\n")
print("Jabatan", tabel.get("Jabatan"), "\n")
print("Gaji Pokok", tabel.get("Gaji_Pokok"), "\n")

NIK ['1990022', '2001077', '2002019', '2002081', '2005099', '2006003', '2006104', '2008160'] 

Nama ['Herman', 'Badar', 'Clara', 'Rista', 'Riani', 'Afif', 'Riven', 'Endah'] 

Jenis Kelamin ['L', 'L', 'P', 'P', 'P', 'L', 'L', 'P'] 

Alamat ['Tangerang', 'Bekasi', 'Depok', 'Bogor', 'Bekasi', 'Karawang', 'Tangerang', 'Jakarta'] 

Divisi ['Machinery', 'Machinery', 'Compressor', 'QC', 'QC', 'Compressor', 'Compressor', 'Machinery'] 

Jabatan ['Manager', 'Staff', 'Staff', 'Staff', 'Operator', 'Operator', 'Operator', 'Operator'] 

Gaji Pokok [100000, 7500000, 7000000, 6500000, 6000000, 5500000, 5500000, 5000000] 



In [25]:
#2
A = np.array([[1,2],
             [4,5],
             [7,8]])
print(A,'\n')
print(A[2,0])
print(A[2,1])

[[1 2]
 [4 5]
 [7 8]] 

7
8


In [26]:
#3
B = np.array([[1,6,9],
              [2,5,8]])
print(B,'\n')
print(B[0,1])
print(B[1,1])

[[1 6 9]
 [2 5 8]] 

6
5


In [27]:
#4
a = np.array([[4,3,8],
              [7,2,5],
              [6,1,9]])
print(a,'\n')
print(a[1,1])
print(a[2,1], '\n')

b = np.array([[4,3,8],
              [7,2,5],
              [6,1,9]])
print(b,'\n')
print(b[0,1])
print(b[0,2])

[[4 3 8]
 [7 2 5]
 [6 1 9]] 

2
1 

[[4 3 8]
 [7 2 5]
 [6 1 9]] 

3
8


In [28]:
a = np.array([[23,35,93,87],
              [92,44,11,83],
              [40,12,11,83],
              [73,67,65,32]])
print(a,'\n')
print('a.', a[1, 1:], '\n')
print('b.', a[2:, 1:3], '\n')
print('c.', a[1:, 1:],'\n')
print('d.', a[1:3, :2], '\n')
print('e.', a[:2, :3],'\n')
print('f.', a[1:, 1])

[[23 35 93 87]
 [92 44 11 83]
 [40 12 11 83]
 [73 67 65 32]] 

a. [44 11 83] 

b. [[12 11]
 [67 65]] 

c. [[44 11 83]
 [12 11 83]
 [67 65 32]] 

d. [[92 44]
 [40 12]] 

e. [[23 35 93]
 [92 44 11]] 

f. [44 12 67]
