In [1]:
#if statement
condition = True
if(condition):
    print('Block of Code dieksekusi!')

Block of Code dieksekusi!


In [3]:
condition = False
if(condition):
    print('Block of Code dieksekusi !')

saat di run tidak muncul apapun karena kondisi nya false atau salah

In [5]:
# angka = 1 
# if(angka >= 0):
#     print(f'{angka} merupakan bilangan positif')
angka = -9 
if(angka >= 0):
    print(f'{angka} merupakan bilangan positif')

saat di run tidak muncul apapun karena tidak memenuhi syarat awal dimana harus lebih dari 0

In [7]:
usia = 17
punya_KTP = 'yes'

if(usia>= 17 and punya_KTP=='yes'):
    print('1. Anda boleh mengikuti ujian pembuatan SIM!')
    
usia = 10
punya_KTP = 'no'

if(usia>= 17 and punya_KTP=='yes'):
    print('2. Anda boleh mengikuti ujian pembuatan SIM!')
    
usia = 16
punya_KTP = 'yes'

if(usia>= 17 and punya_KTP=='yes'):
    print('3. Anda boleh mengikuti ujian pembuatan SIM!')
    
usia = 32
punya_KTP = 'no'

if(usia>= 17 and punya_KTP=='yes'):
    print('4. Anda boleh mengikuti ujian pembuatan SIM!')
    
usia = 23
punya_KTP = 'yes'

if(usia>= 17 and punya_KTP=='yes'):
    print('5. Anda boleh mengikuti ujian pembuatan SIM!')

1. Anda boleh mengikuti ujian pembuatan SIM!
5. Anda boleh mengikuti ujian pembuatan SIM!


In [8]:
usia = 17
punya_KTP = 'yes'

if(usia>= 17 or punya_KTP=='yes'):
    print('1. Anda boleh mengikuti ujian pembuatan SIM!')
    
usia = 10
punya_KTP = 'no'

if(usia>= 17 or punya_KTP=='yes'):
    print('2. Anda boleh mengikuti ujian pembuatan SIM!')
    
usia = 16
punya_KTP = 'yes'

if(usia>= 17 or punya_KTP=='yes'):
    print('3. Anda boleh mengikuti ujian pembuatan SIM!')
    
usia = 32
punya_KTP = 'no'

if(usia>= 17 or punya_KTP=='yes'):
    print('4. Anda boleh mengikuti ujian pembuatan SIM!')
    
usia = 23
punya_KTP = 'yes'

if(usia>= 17 or punya_KTP=='yes'):
    print('5. Anda boleh mengikuti ujian pembuatan SIM!')

1. Anda boleh mengikuti ujian pembuatan SIM!
3. Anda boleh mengikuti ujian pembuatan SIM!
4. Anda boleh mengikuti ujian pembuatan SIM!
5. Anda boleh mengikuti ujian pembuatan SIM!


In [9]:
usia = 25 
punya_KTP = 'no'
suket = 'no'

if(usia >= 17 and (punya_KTP == 'yes' or suket == 'yes')):
    print(" Anda boleh mengikuti ujian pembuatan SIM ! ")

In [10]:
#if-else Statement
if condition:
    print('Block of Code "True" dieksekusi!')
else:
    print('Block of Code "False" dieksekusi!')

Block of Code "False" dieksekusi!


In [11]:
angka = -100
if angka >= 0 and angka < 9:
    print(f'{angka} merupakan bilangan desimal')
else:
     print(f'{angka} bukan termasuk bilangan desimal')  

-100 bukan termasuk bilangan desimal


In [12]:
angka = int(input('Input angka : '))

if angka >= 0 and angka < 9:
    print(f'{angka} merupakan bilangan desimal')
else:
     print(f'{angka} bukan termasuk bilangan desimal')  

Input angka : 3
3 merupakan bilangan desimal


In [13]:
masker = input('Memakai masker [y/n] : ')
vaksin_1 = input('Sudah vaksin ke-1 [y/n] : ')
vaksin_2 = input('Sudah vaksin ke-2 [y/n] : ')
booster = input('Sudah booster ke-1 [y/n] : ')
pcr = input('Hasil pcr [+/-] : ')

if masker=='y' and (vaksin_1=='y' or vaksin_2=='y' or booster=='y') and pcr!='+':
    print('\nAnda boleh membeli tiket pesawat!')
    print('Tetap patuhi prokes!')
    print('Lakukan isoman ketika sudah sampai ditujuan!')
else:
    print ('\nAnda tidak diizinkan membeli tiket pesawat!')

Memakai masker [y/n] : y
Sudah vaksin ke-1 [y/n] : n
Sudah vaksin ke-2 [y/n] : n
Sudah booster ke-1 [y/n] : n
Hasil pcr [+/-] : -

Anda tidak diizinkan membeli tiket pesawat!


In [15]:
#if-elif-else-statement
condition = True
condition1 = False

if condition:
    print('Pilihan utama dieksekusi!')
elif condition1:
    print('Alternatif 1 dieksekusi')
else:
    print('Alternatif terakhir dieksekusi')

Pilihan utama dieksekusi!


In [18]:
angka = int(input('input angka : '))

if angka >= 0 and angka < 9:
    print(f'{angka} merupakan bilangan desimal')
elif angka<0:
    print(f'{angka} merupakan bilangan negatif')
else:
    print(f'{angka} merupakan bilangan asli')

input angka : 14
14 merupakan bilangan asli


In [20]:
nilai =  float(input('Input nilai mahasiswa : '))

if nilai >= 80:
    grade = 'A'
elif nilai >= 70:
    grade = 'B'
elif nilai >= 60:
    grade = 'C'
elif nilai >= 40:
    grade = 'D'
else:
    grade='E'
    
print(f'Anda mendapatkan grade {grade}')

Input nilai mahasiswa : 65
Anda mendapatkan gradeC


In [22]:
saldo = int(input('input jumlah setor tunai: '))
administrasi = 0

if saldo >= 10000:
    administrasi = saldo*0.1
    saldo -= administrasi
elif saldo >= 5000:
    administrasi = saldo*0.05
    saldo -= administrasi
elif saldo >= 1000:
    administrasi = saldo*0.01
    saldo -= administrasi

print(f'\nBiaya adaministrasi Anda sebesar Rp{administrasi}')
print(f'Saldo Anda saat ini adalah Rp {saldo}')

input jumlah setor tunai: 8000

Biaya adaministrasi Anda sebesar Rp400.0
Saldo Anda saat ini adalah Rp 7600.0


In [2]:
presensi  = float(input('Input presensi student\t\t: '))

if presensi >= 85:
    tugas = float(input('input nilai latihan student\t\t: '))
    ujian = float(input('input nilai ujian student\t\t: '))
    nilai = presensi * 0.3 + tugas * 0.3 + ujian * 0.4
    if nilai >= 60:
        print(f'\nStudent lulus dengan nilai {nilai}!')
    else:
        print(f'\nStudent tidak lulus! Nilai yang didapat adalah {nilai}!')
else:
    print('\nStudent tidak lulus karena presensi di bawah 85 %')

Input presensi student		: 54

Student tidak lulus karena presensi di bawah 85 %


In [3]:
nilai = 50
hasil = 'lulus' if nilai >= 60 else 'gagal'
print(hasil)

gagal


In [ ]:
#Loops

In [4]:
condition = True
while condition:
    print('Block of Code dieksekusi')
    condition = False

Block od Code dieksekusi


In [5]:
val = 0 
while val < 10:
    print('Ulangi selama condition bernilai True')
    val = val + 1

print(val)

Ulangi selama condition bernilai True
Ulangi selama condition bernilai True
Ulangi selama condition bernilai True
Ulangi selama condition bernilai True
Ulangi selama condition bernilai True
Ulangi selama condition bernilai True
Ulangi selama condition bernilai True
Ulangi selama condition bernilai True
Ulangi selama condition bernilai True
Ulangi selama condition bernilai True
10


In [6]:
for i in 'Yusup Hidayat Winata':
    print(i)

Y
u
s
u
p
 
H
i
d
a
y
a
t
 
W
i
n
a
t
a


In [7]:
colors = ['merah', 'jingga', 'kuning', 'hijau', 'biru', 'nila', 'ungu']

for color in colors:
    print(color, end=' ')

merah jingga kuning hijau biru nila ungu 

In [8]:
numbers = [1, 4, 9, 2, 5, 8, 7]

for number in numbers:
    print(number, end=' ')

1 4 9 2 5 8 7 

In [9]:
fruits = {'apple':5, 'mango':10, 'banana':3, 'orange':6, 'mangosteen':15}

for fruit in fruits:
    print(fruit)

apple
mango
banana
orange
mangosteen


In [10]:
fruits = {'apple':5, 'mango':10, 'banana':3, 'orange':6, 'mangosteen':15}

for fruit in fruits:
    print(f'Stok {fruit}\t= {fruits[fruit]}')

Stokapple	= 5
Stokmango	= 10
Stokbanana	= 3
Stokorange	= 6
Stokmangosteen	= 15


In [11]:
scores = [90, 80, 70 , 60, 75, 85]
total_scores = 0

for score in scores:
    total_scores = total_scores + score 
    
average = total_scores/len(scores)

print('Total nilai\t=', total_scores)
print('Rata - rata nilai\t=', average)

Total nilai	= 460
Rata - rata nilai	= 76.66666666666667


In [12]:
buah = 'apple', 'mango', 'banana', 'orange', 'mangosteen'
jumlah = 5, 10, 3, 6, 15
harga = 2500, 3000, 5000, 2000, 4000 

for item in zip(buah, jumlah, harga):
    print(item)

('apple', 5, 2500)
('mango', 10, 3000)
('banana', 3, 5000)
('orange', 6, 2000)
('mangosteen', 15, 4000)


In [14]:
buah = 'apple', 'mango', 'banana', 'orange', 'mangosteen'
jumlah = 5, 10, 3, 6, 15
harga = 2500, 3000, 5000, 2000, 4000 

for fruit, count, price in zip (buah, jumlah, harga):
    print(f'Harga {fruit} adalah Rp {price}, sisa stok = {count}')

Harga apple adalah Rp 2500, sisa stok = 5
Harga mango adalah Rp 3000, sisa stok = 10
Harga banana adalah Rp 5000, sisa stok = 3
Harga orange adalah Rp 2000, sisa stok = 6
Harga mangosteen adalah Rp 4000, sisa stok = 15


In [16]:
buah = 'apple', 'mango', 'banana', 'orange', 'mangosteen'
jumlah = 5, 10, 3, 6, 15
harga = 2500, 3000, 5000, 2000, 4000 
total_aset = 0
aset = []

for fruit, count, price in zip (buah, jumlah, harga):
    print(f'Harga {fruit} adalah Rp {price}, sisa stok = {count}')
    total_aset += (price * count)
    aset_satuan = price * count
    aset.append(aset_satuan)
    
print(f'\nTotal aset yang dimiliki = Rp{total_aset}')
print('Aset per item = ', aset)

Harga apple adalah Rp 2500, sisa stok = 5
Harga mango adalah Rp 3000, sisa stok = 10
Harga banana adalah Rp 5000, sisa stok = 3
Harga orange adalah Rp 2000, sisa stok = 6
Harga mangosteen adalah Rp 4000, sisa stok = 15

Total aset yang dimiliki = Rp129500
Aset per item =  [12500, 30000, 15000, 12000, 60000]


In [18]:
for i in range(1, 11):
    print(f'Iterasi ke-{i}')

Iterasi ke-1
Iterasi ke-2
Iterasi ke-3
Iterasi ke-4
Iterasi ke-5
Iterasi ke-6
Iterasi ke-7
Iterasi ke-8
Iterasi ke-9
Iterasi ke-10


In [19]:
for i in range(-11, 1):
    print(f'Iterasi ke-{i}')

Iterasi ke--11
Iterasi ke--10
Iterasi ke--9
Iterasi ke--8
Iterasi ke--7
Iterasi ke--6
Iterasi ke--5
Iterasi ke--4
Iterasi ke--3
Iterasi ke--2
Iterasi ke--1
Iterasi ke-0


In [20]:
numbers = [10, 20, 30, 40, 50, 60]

for i in range(0, len(numbers)):
    numbers[i] = i
    
print(numbers)

[0, 1, 2, 3, 4, 5]


In [21]:
 for i in range(0,3):
        for j in range (0, 3):
            print(i, j, end='\t')
        print('\n')

0 0	0 1	0 2	

1 0	1 1	1 2	

2 0	2 1	2 2	



In [5]:
import numpy as np

data = np.array([[7, 1, 9],
                [8, 6, 5],
                [2, 4, 3]])

for i in data:
    print(i)

[7 1 9]
[8 6 5]
[2 4 3]


In [24]:
data = np.array([[7, 1, 9],
                [8, 6, 5],
                [2, 4, 3]])

for baris in data:
    for kolom in baris:
        print(kolom, end=' ')

7 1 9 8 6 5 2 4 3 

In [25]:
data = np.array([[7, 1, 9],
                [8, 6, 5],
                [2, 4, 3]])

for i in range(0, data.shape[0]):
    for j in range(0, data.shape[1]):
        print(data[i, j], end=' ')

7 1 9 8 6 5 2 4 3 

In [27]:
bilangan = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
nums = []

for bil in bilangan:
    nums.append(bil)
    
print(nums)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [28]:
bilangan = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
nums = [bil for bil in bilangan]
print(nums)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [29]:
bilangan = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
nums = [bil*2+1 for bil in bilangan]
print(nums)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [31]:
bilangan = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
nums = [bil for bil in bilangan if bil%2 == 0]
print(nums)

[0, 2, 4, 6, 8]


In [33]:
for i in range(1, 11):
    if i == 5:
        continue
    print(i, end=' ')

1 2 3 4 6 7 8 9 10 

In [34]:
for i in range(1, 11):
    if i == 5:
        break
    print(i, end=' ')

1 2 3 4 

In [1]:
numbers = [91, 20, 12 , 87, 19, 11, 34, 47, 68, 56]
genap = []
ganjil = []

for number in numbers:
    if number%2 == 0:
        genap.append(number)
    else:
        ganjil.append(number)
        
print('data\t\t: ', numbers)
print('data ganjil\t: ', ganjil)
print('data genap\t: ', genap)

data		:  [91, 20, 12, 87, 19, 11, 34, 47, 68, 56]
data ganjil	:  [91, 87, 19, 11, 47]
data genap	:  [20, 12, 34, 68, 56]


In [2]:
while True:
    print('\n1. hitung luas persegi')
    print('2. hitung luas lingkaran')
    print('3. exit')
    menu = int(input('Input menu pilihan Anda : '))

    if menu == 1:
        s = float(input('\nInput sisi persegi: '))
        print(f'Luas persegi adalah {s*s} cm')
    elif menu == 2:
        r = float(input('\ninput sisi persegi: '))
        print(f'Luas lingkaran adalah {3.14*r*r} cm')
    elif menu == 3:
        print('\nTerimakasih sudah menggunakan program ini :')
        break
    else:
        print('\nMaaf, menu tidak tersedia')



1. hitung luas persegi
2. hitung luas lingkaran
3. exit
Input menu pilihan Anda : 1

Input sisi persegi: 2
Luas persegi adalah 4.0 cm

1. hitung luas persegi
2. hitung luas lingkaran
3. exit
Input menu pilihan Anda : 3

Terimakasih sudah menggunakan program ini :


In [4]:
bb = int(input('Berat Badan dalam kg= ')) 
tb = int(input('Tinggi Badan dalam cm= '))
tbm = tb /100
BMI = bb / tbm**2

if BMI < 18.5:
    print('Kurang Berat Badan')
elif BMI >= 18.5 and BMI < 23:
    print(' Normal ')
elif BMI >= 23 and BMI < 25:
    print(' Kelebihan Berat Badan ')
elif BMI >= 18.5 and BMI < 30:
    print(' Obesitas Tingkat 1 ')
elif BMI >= 30:
    print(' Obesitas Tingkat 2 ')

Berat Badan dalam kg= 67
Tinggi Badan dalam cm= 169
 Kelebihan Berat Badan 


In [11]:
arr = []

while True:
    data = int(input('Input Angka = '))
    if data == 0:
        print("Rata - rata semua angka = ", np.mean(arr))
        break
    else:
        arr.append(data)

Input Angka = 1
Input Angka = 2
Input Angka = 3
Input Angka = 4
Input Angka = 5
Input Angka = 6
Input Angka = 7
Input Angka = 0
Rata - rata semua angka =  4.0


In [10]:
total_nilai = [67, 46, 52, -12, 50, 73, 11, 61, 101, 41, 86, 86, 74, 88, 43, 67, 71, 47, 81, 45, 17, -1, 39, 20, 79]
a = []
b = []
c = []
d = []
e = []
nvld = []
for nilai in total_nilai:
    if nilai < 0 or nilai > 100:
        nvld.append(nilai)
    elif nilai >= 80 and nilai <= 100:
        a.append(nilai)
    elif nilai >= 70 and nilai <= 79:
        b.append(nilai)
    elif nilai >= 50 and nilai <= 69:
        c.append(nilai)
    elif nilai >= 40 and nilai <= 49:
        d.append(nilai)
    elif nilai >= 0 and nilai <= 39:
        e.append(nilai)

    
print("Grade A : ", a)
print("Grade B : ", b)
print("Grade C : ", c)
print("Grade D : ", d)
print("Grade E : ", e)
print("Nilai tidak valid : ", nvld)

Grade A :  [86, 86, 88, 81]
Grade B :  [73, 74, 71, 79]
Grade C :  [67, 52, 50, 61, 67]
Grade D :  [46, 41, 43, 47, 45]
Grade E :  [11, 17, 39, 20]
Nilai tidak valid :  [-12, 101, -1]
